export type SidesIds = 'corp' | 'runner';

export type Publishers = 'null_signal_games' | 'fantasy_flight_games';

export type Formats = 'eternal' | 'ram' | 'snapshot' | 'standard' | 'startup' | 'system_gateway';

export type FileFormat = 'json' | 'txt' | 'otcgn' | 'bbcode' | 'md' | 'jinteki.net';

export type CardTypeIds =
	| 'agenda'
	| 'asset'
	| 'corp_identity'
	| 'event'
	| 'hardware'
	| 'ice'
	| 'operation'
	| 'program'
	| 'resource'
	| 'runner_identity'
	| 'upgrade';

// TODO: get all available subtypes
export type CardSubTypeIds =
	| 'academic'
	| 'ai'
	| 'alliance'
	| 'ambush'
	| 'ap'
	| 'advertisement'
	| 'barrier'
	| 'beanstalk'
	| 'bioroid'
	| 'black_ops'
	| 'bomb'
	| 'caissa'
	| 'cast'
	| 'character'
	| 'chip'
	| 'clan'
	| 'clone'
	| 'cloud'
	| 'code_gate'
	| 'companion'
	| 'condition'
	| 'connection'
	| 'console'
	| 'consumer_grade'
	| 'corp'
	| 'corporation'
	| 'current'
	| 'cybernetic'
	| 'cyborg'
	| 'daemon'
	| 'decoder'
	| 'deep_net'
	| 'deflector'
	| 'department'
	| 'destroyer'
	| 'deva'
	| 'digital'
	| 'directive'
	| 'division'
	| 'double'
	| 'enforcer'
	| 'executive'
	| 'expendable'
	| 'expansion'
	| 'facility'
	| 'fracter'
	| 'g_mod'
	| 'gear'
	| 'genetics'
	| 'government'
	| 'grail'
	| 'gray_ops'
	| 'harmonic'
	| 'hostile'
	| 'icebreaker'
	| 'illicit'
	| 'industrial'
	| 'initiative'
	| 'job'
	| 'killer'
	| 'link'
	| 'location'
	| 'lockdown'
	| 'liability'
	| 'mandate'
	| 'megacorp'
	| 'mod'
	| 'morph'
	| 'mythic'
	| 'next'
	| 'natural'
	| 'observer'
	| 'off_site'
	| 'orgcrime'
	| 'police_department'
	| 'political'
	| 'priority'
	| 'psi'
	| 'public'
	| 'region'
	| 'remote'
	| 'reprisal'
	| 'research'
	| 'ritzy'
	| 'run'
	| 'sabotage'
	| 'security'
	| 'security_protocol'
	| 'seedy'
	| 'sensie'
	| 'sentry'
	| 'source'
	| 'stealth'
	| 'subsidiary'
	| 'sysop'
	| 'terminal'
	| 'transaction'
	| 'trap'
	| 'triple'
	| 'trojan'
	| 'tracer'
	| 'unorthodox'
	| 'unsubstantiated'
	| 'vehicle'
	| 'virtual'
	| 'virus'
	| 'weapon';

export type FactionIds =
	| 'anarch'
	| 'criminal'
	| 'shaper'
	| 'adam'
	| 'apex'
	| 'sunny_lebeau'
	| 'haas_bioroid'
	| 'jinteki'
	| 'nbn'
	| 'weyland_consortium'
	| 'neutral_corp'
	| 'neutral_runner';
